### ISSUE TITLE
"Select" not cascade mode

### ISSUE THREAD

**Issue by jcsena** [danhunsaker/angular-dynamic-forms#43]
as the cascade mode to "select " is performed?

**Comment by danhunsaker** [comment]
I'm afraid I have no idea what you mean, here...

**Comment by jcsena** [comment]
Mmm. ok ,
look at this example..
http://jsfiddle.net/annavester/Zd6uX/

**Comment by danhunsaker** [comment]
So you're looking for a way to do this in ngDynForms?

**Comment by jcsena** [comment]
exactly!  ngDynForms supports this?

**Comment by danhunsaker** [comment]
Only about the same way the jsFiddle you shared does.  All ngDynForms does is let you build the form; logic is beyond its scope.  For now, the idea is to find existing implementations of non-HTML5 controls (that is, controls that aren't natively part of the HTML spec) and have ngDynForms create one of them using the control's `attributes`.

That said, I'm planning a major refactor that will support plugins, and this sounds like a perfect plugin candidate to me.

**Comment by jcsena** [comment]
OK, 
I understand I will figure then inject the information on my main controller,

another question ,

```javascript
  {
    "type": "select",
    "model": "select",
    "label": "select",
    "empty": "empty",
    "options": {
      "second": {
        "label": "second option",
        "group": "first group"
      },
      "third": {
        "label": "third option",
        "group": "second group"
      }
    }
  }
```
in options may have an array and not an object 
Ex: 

```javascript

  "options": [
     {
       "name": "second"
        "label": "second option",
        "group": "first group"
      },
     {
        "name": "third"
        "label": "third option",
        "group": "second group"
      }
    ]
```

**Comment by danhunsaker** [comment]
That's something I'm working on, and haven't had the chance to push, yet.  Though it'll be `val` instead of `name`.

**Comment by rmacteague** [comment]
Any idea when options for selects and radios will be in array form will be implemented?

**Comment by jcsena** [comment]
@rmacteague  http://stackoverflow.com/questions/18723399/cascading-select-dropdowns
