### ISSUE TITLE
Pre-processing form data

### ISSUE THREAD

**Issue by sh4nks** [danhunsaker/angular-dynamic-forms#50]
Hey!

I am getting my data from a server and I have to pre-process is before it can be used in dynamic-forms.
My problem is, that the data is somehow not available in the dynform.

The controller looks like this:
```
myControllers.controller('ProjectUserInfoCtrl', ['$scope', '$http', '$routeParams', 'Project', 'ProjectField',
  function($scope, $http, $routeParams, Project, ProjectField) {

      $scope.formData = {};
      $scope.formTemplate = [];

    var project = Project.get({ projectId: $routeParams.projectId }, function(data) {
        $scope.project = data.projects;
    });

    var fields = ProjectField.get({ projectId: $routeParams.projectId }, function(data) {
        $scope.fields = data.fields;
        $.each($scope.fields, function(k, v) {
            $scope.formTemplate.push({
                "type": "text",
                "label": v.name,
                "model": v.name
            });
        });
    });
}]);
```

Thanks in advance!

**Comment by danhunsaker** [comment]
Dynamic updating isn't implemented, yet, so you'd have to add the `<dynamic-form>` tag to the DOM, and trigger a recompile, *after* loading and preprocessing the template.  I'm working on dynamic updates, but it's not an easy task, and I don't have a lot of time for free work, so it will probably be a while.

**Comment by sh4nks** [comment]
Ah okay thanks!

I solved it for now like this:
I am using a variable which to check if all the data is already loaded and if it's loaded I am displaying the form.

```html
<dynamic-form template="formTemplate"
    ng-model="formData"
    ng-submit="processForm()"
    ng-if="dataHasLoaded">
</dynamic-form>
```

```javascript
$scope.dataHasLoaded = false;
var fields = ProjectField.get({ projectId: $routeParams.projectId }, function(data) {
    $scope.fields = data.fields;
    $scope.dataHasLoaded = true;
    $.each($scope.fields, function(k, v) {
        // pre processing fields
    });

});
```

There might be better solutions for this but I am quite new to angularjs and this gets the job done :)

**Comment by danhunsaker** [comment]
That's actually quite clever, using `ng-if` - I hadn't thought about that, myself.  Good use of Angular!

I'd probably set `$scope.dataHasLoaded` to `true` after the `$.each()` rather than before, but I'm overly cautious at times.  Either way, nice solution!
