### ISSUE TITLE
Unknown provider: dynformProvider <- dynform <- LoginCtrl

### ISSUE THREAD

**Issue by php5engineer** [danhunsaker/angular-dynamic-forms#62]
"Error: [$injector:unpr] Unknown provider: dynformProvider <- dynform <- LoginCtrl
http://errors.angularjs.org/1.4.8/$injector/unpr?p0=dynformProvider%20%3C-                   0ynform%20%3C-%20LoginCtrl
minErr/<@http://127.0.0.1:8000/app/bower_components/angular/angular.js:68:12
createInjector/providerCache.$injector<@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4334:19
getService@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4482:39
createInjector/instanceCache.$injector<@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4339:28
getService@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4482:39
invoke@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4514:1
instantiate@http://127.0.0.1:8000/app/bower_components/angular/angular.js:4531:27
$ControllerProvider/this.$get</<@http://127.0.0.1:8000/app/bower_components/angular/angular.js:9197:18
ngViewFillContentFactory/<.link@http://127.0.0.1:8000/app/bower_components/angular-route/angular-route.js:977:26
invokeLinkFn@http://127.0.0.1:8000/app/bower_components/angular/angular.js:8841:9
nodeLinkFn@http://127.0.0.1:8000/app/bower_components/angular/angular.js:8335:1
compositeLinkFn@http://127.0.0.1:8000/app/bower_components/angular/angular.js:7731:13
publicLinkFn@http://127.0.0.1:8000/app/bower_components/angular/angular.js:7611:30
createBoundTranscludeFn/boundTranscludeFn@http://127.0.0.1:8000/app/bower_components/angular/angular.js:7749:1
controllersBoundTransclude@http://127.0.0.1:8000/app/bower_components/angular/angular.js:8362:18
update@http://127.0.0.1:8000/app/bower_components/angular-route/angular-route.js:935:25
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://127.0.0.1:8000/app/bower_components/angular/angular.js:16374:15
commitRoute/<@http://127.0.0.1:8000/app/bower_components/angular-route/angular-route.js:619:15
processQueue@http://127.0.0.1:8000/app/bower_components/angular/angular.js:14792:28
scheduleProcessQueue/<@http://127.0.0.1:8000/app/bower_components/angular/angular.js:14808:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://127.0.0.1:8000/app/bower_components/angular/angular.js:16052:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://127.0.0.1:8000/app/bower_components/angular/angular.js:15870:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://127.0.0.1:8000/app/bower_components/angular/angular.js:16160:13
done@http://127.0.0.1:8000/app/bower_components/angular/angular.js:10589:36
completeRequest@http://127.0.0.1:8000/app/bower_components/angular/angular.js:10787:7
requestLoaded@http://127.0.0.1:8000/app/bower_components/angular/angular.js:10728:1
"

What does this error mean?

**Comment by danhunsaker** [comment]
If you visit the first link in this error message, it explains the issue fairly well.  Make sure the dynForms script is loading before your app script(s), and double-check your spelling and capitalization.

**Comment by php5engineer** [comment]
It was because I've injected 'dynform' into controller, not module
