### ISSUE TITLE
 File Upload Issue...Last 1 for this project I hope

### ISSUE THREAD

**Issue by abku** [danhunsaker/angular-dynamic-forms#65]
@danhunsaker 
Do you have a sample of how file upload works?  I have used the dynamic load and post based on @SamanShafigh (issue #55).  The parameters that gets posted to my asp script is:
undefined[id]=2&undefined[rID]=bb445af5-846a-43ec-b89e-d3728a3c5365&undefined[task]=This+is+my+Task&undefined
[duedate]=&undefined[file]=%5Bobject+FileList%5D

I can fix the undefined part but file gets returned as an object and I cannot seem to upload the file to the server.  Can you please provide me with any help in this matter?

**Comment by abku** [comment]
Marking this as closed as no help was received.  I had to create a .net project and load the file upload via iframe and use .net controls instead of the ones provided.  Was hoping that someone could help but no answer/help/response for 12 days made me take the drastic measure.

**Comment by danhunsaker** [comment]
Apologies for the delay.  I've been kept away from the Internet for the past several weeks, so am just now getting a chance to address issues.

I highly recommend checking the links in the description of the `file` control type.  The link for the FileReader service shows how to use it to retrieve file contents.
