### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by Stusaw** [danhunsaker/angular-dynamic-forms#75]
Has anyone got this working as I can't appear to. It just renders an empty form dispite being passed a collection.

**Comment by danhunsaker** [comment]
Regretfully, I haven't been able to maintain this project and keep it up to date with the latest versions of Angular.  There's a section on alternatives in the README that I recommend checking out instead.

**Comment by Stusaw** [comment]
Ok, Thanks for letting me know. Looked really awesome too!!

**Comment by danhunsaker** [comment]
Thanks!  Apparently others thought so, too, because theirs are even better.
