### ISSUE TITLE
Refresh directive upon attrs.template (stdFormTemplate) change

### ISSUE THREAD

**Issue by boubasla** [danhunsaker/angular-dynamic-forms#79]
How you can resfresh dynamic-form when dynamically stdFormTemplate change in controller
example:

C O N T R O L L E R
 //first init -- rendered correctly by directive.
 $scope.stdFormTemplate =  {
      "fieldset": {..............}}

$scope.changeModel = function () {
 $scope.stdFormTemplate =  {
      "fieldset": {..............}}
 }

**Comment by danhunsaker** [comment]
See #6
